In [ ]:
%pip install pandas numpy pillow tqdm torch torchvision

In [4]:
import pandas as pd 
import os

In [5]:
cat_path = r"C:\Users\Wanna\Desktop\Fashion FYP\data\DeepFashion\list_category_cloth.txt" 
categories = pd.read_csv( 
    cat_path, sep=r"\s+", 
    skiprows=1, 
    names=["category_name", "category_type"] 
    ) 
categories = categories[categories["category_name"] != "category_name"] 
categories = categories.reset_index(drop=True) 
#DeepFashion category IDs are index + 1 
categories["category_id"] = categories.index + 1

categories.head(10)

  category_name category_type  category_id
0        Anorak             1            1
1        Blazer             1            2
2        Blouse             1            3
3        Bomber             1            4
4   Button-Down             1            5
5      Cardigan             1            6
6       Flannel             1            7
7        Halter             1            8
8        Henley             1            9
9        Hoodie             1           10

In [6]:
img_category_path = r"C:\Users\Wanna\Desktop\Fashion FYP\data\DeepFashion\list_category_img.txt"
img_categories = pd.read_csv( 
    img_category_path, 
    sep=r"\s+", 
    skiprows=1, 
    names=["image", "category"] 
    )
img_categories["category"] = pd.to_numeric( 
    img_categories["category"], errors="coerce" )

img_categories = img_categories.dropna(subset=["category"])

img_categories["category"] = img_categories["category"].astype(int)

tops_names = ["Blouse", "Tee", "Shirt", "Sweater", "Hoodie", "Tank", "Top"]

tops_category_ids = categories[
    categories["category_name"].isin(tops_names)
].index + 1   #index + 1 because DeepFashion is 1-indexed

tops_df = img_categories[
    img_categories["category"].isin(tops_category_ids)
]

print(f"Top images: {len(tops_df)}")
tops_df.head()

Top images: 104122

C:\Users\Wanna\AppData\Local\Temp\ipykernel_27968\2757386986.py:2: DtypeWarning: Columns (0: category) have mixed types. Specify dtype option on import or set low_memory=False.
  img_categories = pd.read_csv(

                                             image  category
1  img/Sheer_Pleated-Front_Blouse/img_00000001.jpg         3
2  img/Sheer_Pleated-Front_Blouse/img_00000002.jpg         3
3  img/Sheer_Pleated-Front_Blouse/img_00000003.jpg         3
4  img/Sheer_Pleated-Front_Blouse/img_00000004.jpg         3
5  img/Sheer_Pleated-Front_Blouse/img_00000005.jpg         3

In [10]:
image_root = r"C:\Users\Wanna\Desktop\Fashion FYP\img"

def image_exists(rel_path):
    return os.path.exists(os.path.join(image_root, rel_path))

tops_df["exists"] = tops_df["image"].apply(image_exists)

print(tops_df["exists"].value_counts())

exists
True    104122
Name: count, dtype: int64